import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Mulish } from 'next/font/google'

const mulish = Mulish({ 
  weight:["300","400","500","600","700","800","900"],  
  subsets: ['latin'] ,
  display:'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body className='bg-gradient-to-r  from-indigo-900 via-purple-900 to-pink-900 '>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
